In [89]:
import sys
sys.path.append('../')

In [90]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine, Table, text

from config import RUTA_UNIDAD_ONE_DRIVE
from config import RUTA_LOCAL_ONE_DRIVE
from config import POSTGRES_UTEA

In [113]:
USER_DB = POSTGRES_UTEA['USER']
PASS_DB = POSTGRES_UTEA['PASSWORD']
HOST_DB = POSTGRES_UTEA['HOST']
PORT_DB = POSTGRES_UTEA['PORT']
NAME_DB = POSTGRES_UTEA['DATABASE']

ENGINE = create_engine(f'postgresql+psycopg://{USER_DB}:{PASS_DB}@{HOST_DB}:{PORT_DB}/{NAME_DB}')

PATH_GRUPOS_COSECHA = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\DATA\GRUPO_TRABAJO.xlsx'
PATH_INSTITUCIONES = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\DATA\INSTITUCIONES.xlsx'

PATH_PLAN_ZAFRA = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\ZAFRAS - ZAFRA 2026\PLAN_ZAFRA_2026\Plan de Zafra 2026 Actualizado.xlsx'
PATH_GRUPOS_ECO = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\ZAFRAS - ZAFRA 2026\UCAF\GRUPOS ECONOMICOS 2026.xlsx'
PATH_COMPROMISO_FIRMADO = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\ZAFRAS - ZAFRA 2026\UCAF\FIRMA DE COMPROMISOS 2026.xlsx'

PATH_LAICA = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\COOR_GERENCIA_CANA - PARTES_LAICA\LAICA 6_2026.xlsx'
PATH_TCH = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2026\DATA\TCHS.xlsx'
PATH_XLSX_ACCESOS_AGROCITTCA = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AGRO-CITTCA\LISTA.xlsx'

In [114]:
def cargar_codigos_trabajo():
    try:
        df = pd.read_excel(PATH_GRUPOS_COSECHA, sheet_name='2026')
        df = df[['CODIGO CAÑERO', 'NOMBRE CAÑERO', 'GRUPO TRABAJO', 'INS', 'DELEGADO']]
        df = df.rename(columns={
            'CODIGO CAÑERO': 'cod_ca',
            'NOMBRE CAÑERO': 'nom_ca',
            'GRUPO TRABAJO': 'cod_tra',
            'INS': 'inst',
            'DELEGADO': 'delegado'
        })
        df = df.sort_values(by=['cod_tra', 'inst', 'cod_ca'])
        return df
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_cod_tra_a_db(df):
    # Convertir tipos para Postgres
    df['inst']     = df['inst'].astype('Int64')
    df['cod_ca']   = df['cod_ca'].astype('Int64')
    df['cod_tra']  = df['cod_tra'].astype('Int64')
    df['nom_ca']   = df['nom_ca'].astype(str)

    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_codigos_trabajo RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_codigos_trabajo',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de codigos cosecha")

def cargar_instituciones():
    try:
        df = pd.read_excel(PATH_INSTITUCIONES)
        return df
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_instituciones_a_db(df):
    # Convertir tipos para Postgres
    df['cod']     = df['cod'].astype('Int64')
    df['nom_inst']   = df['nom_inst'].astype(str)
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_instituciones RESTART IDENTITY'))
        # Insertar nuevos datos
        df.to_sql(
            name='data_instituciones',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de instituciones")

def cargar_plan_zafra():
    try:
        df = pd.read_excel(PATH_PLAN_ZAFRA, sheet_name='plan de zafra 2026')
        df = df[['INST.', 'COD. CAÑERO', 'NOMBRE DEL CAÑERO', 'TONELADAS COMPROMISO']]        
        df = df.rename(columns={
            'INST.': 'inst',
            'COD. CAÑERO': 'cod_ca',
            'NOMBRE DEL CAÑERO': 'nom_ca',
            'TONELADAS COMPROMISO': 'compromiso'
        })
        df = df.sort_values(by=['inst', 'cod_ca'])
        return df
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_plan_zafra_a_db(df):
    # Convertir tipos para Postgres
    df['inst']     = df['inst'].astype('Int64')
    df['cod_ca']   = df['cod_ca'].astype('Int64')
    df['nom_ca']   = df['nom_ca'].astype(str)
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_plan_zafra RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_plan_zafra',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de plan de zafra")
    
def get_resumen_estimativa():
    try:
        query = "select unidad_01, unidad_03, categoria, sum(area) as area from catastro_iag.estimativa group by unidad_01, unidad_03, categoria"
        df = pd.read_sql(query, ENGINE)
        return df
    except Exception as e:
        print("❌ Error al leer datos de ESTIMATIVA:", e)
        return pd.DataFrame()
    return None

def cargar_resumen_estimativa_a_db(df):
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_resumen_estimativa RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_resumen_estimativa',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de resumen estimativa")
    
def cargar_laica():
    try:
        df = pd.read_excel(PATH_LAICA, sheet_name='Datos')
        df = df[['Fecha', 'Cod. Cañero', 'Nombre Cañero', 'kg Caña Neta', '% Material Extraño (Inspección)', 'kg Caña Límpia', '% Pureza', 'PCF', 'Tipo Cosecha', 'Tipo Caña']]        
        df = df.rename(columns={
            'Fecha': 'fecha',
            'Cod. Cañero': 'cod_ca',
            'Nombre Cañero': 'nom_ca',
            'kg Caña Neta': 'kg_entregado',
            '% Material Extraño (Inspección)': 'me', 
            'kg Caña Límpia' : 'kg_cana_limpia',
            '% Pureza': 'pureza', 
            'PCF': 'pcf', 
            'Tipo Cosecha': 'tipo_cosecha', 
            'Tipo Caña': 'tipo_cana'
        })
        return df
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_datos_laica_a_db(df):
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_laica RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_laica',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de datos laica")

def cargar_grupos_eco():
    try:
        df = pd.read_excel(PATH_GRUPOS_ECO, sheet_name='grupos economicos')
        df = df.rename(columns={
            'DEUDOR': 'deudor',
            'CODIGO': 'codigo',
            'NOMBRE': 'nombre',
            'GRUPO ECONOMICO': 'grupo_economico',
            'COD. INSTITUCION': 'cod_institucion',
            'ORDEN': 'orden',
            'CABEZA DEL GRUPO': 'cabeza_del_grupo'
        })
        return df
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_datos_grupo_eco_a_db(df):
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_grupo_eco RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_grupo_eco',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de datos grupos economicos")

def cargar_compromiso_firmado():
    try:
        df = pd.read_excel(PATH_COMPROMISO_FIRMADO, sheet_name='firmas')
        df = df.rename(columns={
            'CITE': 'cod',
            'TONELADAS': 'toneladas',
            'CODIGO GRUPO': 'grupo_eco'
        })
        df['cod'] = 0
        return df[['cod', 'toneladas', 'grupo_eco']]
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_compromiso_firmado_a_db(df):
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_compromiso_firmado RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_compromiso_firmado',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de datos grupos economicos")

def cargar_estimativa_lote_a_db(df):
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_estimativa_lote RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_estimativa_lote',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de datos estimativa lote")

def cargar_xlsx_tchs():
    try:
        df = pd.read_excel(PATH_TCH)
        return df
    except Exception as e:
        print(f"❌ Error al cargar el archivo: {e}")
        return pd.DataFrame()

def cargar_estimativa_lote_a_db(df):
    with ENGINE.begin() as conn:  # Inicia transacción
        # Vaciar la tabla y reiniciar secuencia
        conn.execute(text(f'TRUNCATE TABLE catastro_iag.data_estimativa_lote RESTART IDENTITY'))
        
        # Insertar nuevos datos
        df.to_sql(
            name='data_estimativa_lote',
            con=conn,  # conexión cruda dentro de la transacción
            schema='catastro_iag',
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Se ha actualziado la tabla de datos estimativa lote")

def get_propiedades_estimativa():
    try:
        query = "select distinct(unidad_01), unidad_02 from catastro_iag.estimativa order by unidad_01"
        df = pd.read_sql(query, ENGINE)
        return df
    except Exception as e:
        print("❌ Error al leer datos de ESTIMATIVA:", e)
        return pd.DataFrame()
    return None

def get_estimativa_idd():
    try:
        query = "SELECT unidad_01, unidad_03, unidad_05, categoria, area, unidad_01 || '|' || categoria idd FROM catastro_iag.estimativa"
        df = pd.read_sql(query, ENGINE)
        return df
    except Exception as e:
        print("❌ Error al leer datos de ESTIMATIVA:", e)
        return pd.DataFrame()
    return None

In [115]:
codigos_trabajo = cargar_codigos_trabajo()
## Elimina nulos de la columna inst
codigos_trabajo.dropna(subset=['inst'], inplace=True)
cargar_cod_tra_a_db(codigos_trabajo)

✅ Se ha actualziado la tabla de codigos cosecha

In [116]:
instituciones = cargar_instituciones()
cargar_instituciones_a_db(instituciones)

✅ Se ha actualziado la tabla de instituciones

In [117]:
plan_zafra = cargar_plan_zafra()
## Elimina nulos de la columna inst
plan_zafra.dropna(subset=['inst'], inplace=True)
cargar_plan_zafra_a_db(plan_zafra)

✅ Se ha actualziado la tabla de plan de zafra

In [118]:
resumen_estimativa = get_resumen_estimativa()
cargar_resumen_estimativa_a_db(resumen_estimativa)

✅ Se ha actualziado la tabla de resumen estimativa

In [119]:
datos_laica = cargar_laica()
datos_laica['tn_entregado'] = datos_laica['kg_entregado'] / 1000
datos_laica['tn_cana_limpia'] = datos_laica['kg_cana_limpia'] / 1000
cargar_datos_laica_a_db(datos_laica)

✅ Se ha actualziado la tabla de datos laica

In [120]:
datos_grupo_eco = cargar_grupos_eco()
cargar_datos_grupo_eco_a_db(datos_grupo_eco)

✅ Se ha actualziado la tabla de datos grupos economicos

In [121]:
datos_compromiso_firmado = cargar_compromiso_firmado()
datos_compromiso_firmado.dropna(subset=['grupo_eco'], inplace=True)
cargar_compromiso_firmado_a_db(datos_compromiso_firmado)

✅ Se ha actualziado la tabla de datos grupos economicos

In [122]:
tchs = cargar_xlsx_tchs()
tchs["idd"] = tchs.apply(lambda row: f"{row['cod_prop']}|{row['categoria']}", axis=1)
tchs.head(3)

   cod_prop nom_prop  categoria categoria 2  tch eval  tch_ajustado  idd
0         1   SONIMA          1        Nulo         0             0  1|1
1         1   SONIMA          2    Muy Bajo        20            20  1|2
2         1   SONIMA          3  Medio Bajo        30            30  1|3

In [123]:
estimativa = get_estimativa_idd()
estimativa.head(3)

   unidad_01  unidad_03 unidad_05  categoria      area  idd
0          1        388       L78          3  0.009742  1|3
1          1        388       L78          4  0.077939  1|4
2          1        388       L78          5  0.292270  1|5

In [124]:
df_join = pd.merge(estimativa, tchs, on="idd", how="inner")
df_join['produccion'] = df_join['area'] * df_join['tch eval']

In [125]:
df_join = df_join[['unidad_01', 'unidad_03', 'unidad_05', 'area', 'produccion']]
df_join

         unidad_01  unidad_03 unidad_05      area  produccion
0                1        388       L78  0.009742    0.292270
1                1        388       L78  0.077939    3.117542
2                1        388       L78  0.292270   16.074827
3                1        388       L78  0.000000    0.000000
4                1        388       L78  0.038969    2.143310
...            ...        ...       ...       ...         ...
1045446        110        544      L8.2  0.030191    1.509569
1045447        110        544      L8.2  0.010064    0.603828
1045448        110        544      L8.2  0.070447    5.635726
1045449        110        544      L8.2  0.000000    0.000000
1045450        110        544      L8.2  0.010064    0.805104

[1045451 rows x 5 columns]

In [126]:
df_res = df_join.groupby(["unidad_01", "unidad_03", "unidad_05"])[["area", "produccion"]].sum().reset_index()

In [127]:
df_res[["area", "produccion"]] = df_res[["area", "produccion"]].round(2)

In [128]:
df_res

       unidad_01  unidad_03 unidad_05   area  produccion
0              1        388       L69   2.52      229.89
1              1        388       L78   9.83      625.26
2              1        388       L85   1.68       95.74
3              1      18358       L70  10.42      907.77
4              1      18358     L71.1   6.29      555.33
...          ...        ...       ...    ...         ...
10333       2401      42746      L4.2   8.08      377.62
10334       2402      42699        L1  39.47     2550.44
10335       2402      42699        L2  20.89     1361.72
10336       2404      42109        L2   4.95      287.93
10337       2404      42109        L3   2.70      126.10

[10338 rows x 5 columns]

In [129]:
cargar_estimativa_lote_a_db(df_res)

✅ Se ha actualziado la tabla de datos estimativa lote

In [130]:
# obtiene el xlsx de TCHs
tch_xlsx = cargar_xlsx_tchs()
# 
props_estimativa = get_propiedades_estimativa()
lista_cods_props_tch_xlsx = list(set(tch_xlsx['cod_prop']))
lista_cods_props_estiamtiva = list(set(props_estimativa['unidad_01']))

In [131]:
cods_eliminar_de_xlsx = [x for x in lista_cods_props_tch_xlsx if x not in lista_cods_props_estiamtiva]
print('CODIGOS A ELIMINAR DE XLSX:')
cods_eliminar_de_xlsx

CODIGOS A ELIMINAR DE XLSX:

[27,
 67,
 93,
 141,
 308,
 331,
 359,
 466,
 471,
 491,
 494,
 573,
 574,
 575,
 658,
 669,
 693,
 711,
 721,
 780,
 824,
 832,
 841,
 856,
 870,
 955,
 958,
 992,
 1024,
 1036,
 1042,
 1055,
 1074,
 1083,
 1125,
 1139,
 1178,
 1190,
 1207,
 1220,
 1225,
 1239,
 1251,
 1271,
 1304,
 1321,
 1372,
 1379,
 1391,
 1392,
 1420,
 1424,
 1431,
 1432,
 1436,
 1445,
 1492,
 1498,
 1516,
 1523,
 1524,
 1541,
 1547,
 1567,
 1608,
 1610,
 1615,
 1619,
 1628,
 1693,
 1718,
 1722,
 1742,
 1767,
 1802,
 1863,
 1866,
 1894,
 1925,
 1947,
 1957,
 1971,
 2000,
 2001,
 2021,
 2044,
 2050,
 2091,
 2102,
 2109,
 2111,
 2137,
 2139,
 2143,
 2146,
 2154,
 2181,
 2226,
 2233,
 2236,
 2242,
 2243,
 2244,
 2245,
 2248,
 2261,
 2263,
 2264,
 2269,
 2277,
 2278,
 2291,
 2293,
 2317]

In [132]:
cods_agregar_a_xlsx = [x for x in lista_cods_props_estiamtiva if x not in lista_cods_props_tch_xlsx]
print('CODIGOS A AGREGAR A XLSX:')
cods_agregar_a_xlsx

CODIGOS A AGREGAR A XLSX:

[]

In [133]:
df_filtrado = props_estimativa[props_estimativa['unidad_01'].isin(cods_agregar_a_xlsx)]
df_filtrado

Empty DataFrame
Columns: [unidad_01, unidad_02]
Index: []