In [28]:
import sys
sys.path.append('..')

import os
import shutil
from sqlalchemy import create_engine, text
import geopandas as gpd
import pandas as pd
from geopandas.tools import sjoin
from shapely.geometry import Point, Polygon, MultiPolygon, MultiPoint
from shapely import wkb
import simplekml

from utilities_amigocloud import AmigocloudFunctions

from config import RUTA_UNIDAD_ONE_DRIVE
from config import RUTA_LOCAL_ONE_DRIVE
from config import API_AMIGOCLOUD_TOKEN_ADM
from config import POSTGRES_UTEA

RUTA_COMPLETA = os.path.join(RUTA_UNIDAD_ONE_DRIVE, RUTA_LOCAL_ONE_DRIVE)

In [29]:
# leer los dos shps de siembra y puntos de planificacion
#PATH_SIEMBRA = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2025\SHP\SIEMBRAS_2.shp'
#PATH_CAT = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2025\SHP\CATASTRO_S09_MIERCOLES.shp'
PATH_KML = RUTA_UNIDAD_ONE_DRIVE + r'\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN'

#gdf_siembras = gpd.read_file(PATH_SIEMBRA)
#gdf_cat = gpd.read_file(PATH_CAT)

In [30]:
def obtener_engine():
    return create_engine(
        f"postgresql+psycopg2://{POSTGRES_UTEA['USER']}:{POSTGRES_UTEA['PASSWORD']}@{POSTGRES_UTEA['HOST']}:{POSTGRES_UTEA['PORT']}/{POSTGRES_UTEA['DATABASE']}"
    )

def obtener_planificacion_no_procesado():
    engine = obtener_engine()
    try:
        query = """
            SELECT id_os, geom, cod_ca, nom_ca, obs, procesado, producto, dosis, semana_plan
            FROM drones_control_bio.planificacion_ctrl_bio
            WHERE procesado=false;
        """
        gdf = gpd.read_postgis(query, engine, geom_col='geom')
        return gdf
    except Exception as e:
        print(f"❌ Error en la consulta: {e}")
        return gpd.GeoDataFrame()
    return None

def get_catastro():
    engine = obtener_engine()
    try:
        query = f'''
            SELECT * FROM catastro_iag.catastro
        '''
        gdf = gpd.read_postgis(query, engine, geom_col='geom')
        return gdf
    except Exception as e:
        print(f"❌ Error al obtener la capa de catastro: {e}")
        return gpd.GeoDataFrame()
    return None

def get_siembras():
    engine = obtener_engine()
    try:
        query = f'''
            SELECT * FROM drones_control_bio.siembra
        '''
        gdf = gpd.read_postgis(query, engine, geom_col='geom')
        return gdf
    except Exception as e:
        print(f"❌ Error al obtener capa de siembras: {e}")
        return gpd.GeoDataFrame()
    return None

def obtener_parte_diario_por_id_os(id_os):
    engine = obtener_engine()
    try:
        query = f"""
            SELECT * FROM drones_control_bio.parte_diario_ctrl_bio where os = {id_os}
        """
        gdf = gpd.read_postgis(query, engine, geom_col='geom')
        return gdf
    except Exception as e:
        print(f"❌ Error en la consulta: {e}")
        return gpd.GeoDataFrame()
    return None

def obtener_parte_diario_sin_planificar():
    engine = obtener_engine()
    try:
        query = f"""
            SELECT * FROM drones_control_bio.parte_diario_ctrl_bio where estado IS NULL
        """
        gdf = gpd.read_postgis(query, engine, geom_col='geom')
        return gdf
    except Exception as e:
        print(f"❌ Error en la consulta: {e}")
        return gpd.GeoDataFrame()
    return None

def obtener_parte_diario_planificado():
    engine = obtener_engine()
    try:
        query = f"""
            SELECT * FROM drones_control_bio.parte_diario_ctrl_bio where estado = 'PLANIFICADO'
        """
        gdf = gpd.read_postgis(query, engine, geom_col='geom')
        return gdf
    except Exception as e:
        print(f"❌ Error en la consulta: {e}")
        return gpd.GeoDataFrame()
    return None

def filtrar_os_y_quitar_caracteres(gdf, ors):
    # filtrar la semana de interes
    gdf_puntos_select = gdf[gdf['id_os'] == ors]
    gdf_puntos_sem = gdf_puntos_select.copy()
    #quita caracteres especiales
    gdf_puntos_sem['nom_ca'] = gdf_puntos_sem['nom_ca'].str.replace(r'[\r\n\t]', '', regex=True)
    return gdf_puntos_sem

def marcar_como_procesado(id_os):
    engine = obtener_engine()  # tu función que crea el engine
    try:
        with engine.begin() as conn:
            query = text("""
                UPDATE drones_control_bio.planificacion_ctrl_bio
                SET procesado = true
                WHERE id_os = :id_os
            """)
            conn.execute(query, {"id_os": id_os})
            print(f"✔️ id_os {id_os} marcado como procesado.")
    except Exception as e:
        print(f"❌ Error al actualizar: {e}")
    return None

def marcar_como_planificado(id_lote):
    engine = obtener_engine()  # tu función que crea el engine
    try:
        with engine.begin() as conn:
            query = text("""
                UPDATE drones_control_bio.parte_diario_ctrl_bio
                SET estado = 'PLANIFICADO'
                WHERE id = :id_lote
            """)
            conn.execute(query, {"id_lote": id_lote})
            print(f"✔️ id_lote {id_lote} marcado como PLANIFICADO.")
    except Exception as e:
        print(f"❌ Error al actualizar: {e}")
    return None

def crear_puntos_individuales(gdf_fila):
    # Obtener la geometría del único registro
    geom = gdf_fila.iloc[0][gdf_fila.geometry.name]
    # Verificar si es MultiPoint
    if isinstance(geom, MultiPoint):
        # Crear un nuevo registro por cada punto
        registros = []
        for punto in geom.geoms:
            nuevo = gdf_fila.iloc[0].copy()
            nuevo[gdf_fila.geometry.name] = punto
            registros.append(nuevo)
        return gpd.GeoDataFrame(registros, geometry=gdf_fila.geometry.name, crs=gdf_fila.crs)
    else:
        # Si ya es un punto, retornar tal cual
        return gdf_fila.copy()

def definir_lotes_solicitud(gdf_puntos_indi):
    id_os = gdf_puntos_indi.iloc[0]['id_os']
    codigo_ca = gdf_puntos_indi.iloc[0]['cod_ca']
    nombre_ca = gdf_puntos_indi.iloc[0]['nom_ca']
    semana_plan = gdf_puntos_indi.iloc[0]['semana_plan']
    
    # Crear un GeoDataFrame vacío para almacenar los puntos que no intersectan con ningún polígono de siembra
    puntos_indi_solicitado = gdf_puntos_indi[~gdf_puntos_indi.geometry.apply(lambda point: any(gdf_siembras.contains(point)))]
    
    # identifoca los lotes que se intersectan
    gdf_lotes_cat = gpd.sjoin(gdf_cat, puntos_indi_solicitado, how='inner', predicate='intersects')    
    
    # filtra los lotes intersectados en la capa original
    poligonos_intersect_cat = gdf_cat.loc[gdf_cat.index.isin(gdf_lotes_cat.index)]
    
    # copy
    poligonos_intersect_cat = poligonos_intersect_cat.copy()
    poligonos_intersect_cat = poligonos_intersect_cat[['unidad_01', 'unidad_02', 'unidad_03', 'unidad_04', 'unidad_05', 'area', 'soca', 'zona', 'geom']]
    poligonos_intersect_cat["soca"] = poligonos_intersect_cat["soca"].fillna(0)
    # Cambiar el nombre de la columna 'old_name' a 'new_name'
    poligonos_intersect_cat.rename(columns={'zona': 'inst'}, inplace=True)
    # CAMBIAR NOMBRE DATOS DE UNIDAD_03 Y UNDIAD_04 DE LOTES SOLICITADOS A LO INDICADO EN LOS PUNTOS
    poligonos_intersect_cat['unidad_03'] = codigo_ca
    poligonos_intersect_cat['unidad_04'] = nombre_ca
    poligonos_intersect_cat['semana_plan'] = semana_plan
    
    # agrega los campos faltantes
    poligonos_intersect_cat['origen'] = 'SOLICITUD'
    poligonos_intersect_cat['dias'] = 0
    poligonos_intersect_cat['fecha'] = ''
    poligonos_intersect_cat['os'] = id_os
    return poligonos_intersect_cat

def definir_lotes_siembra(gdf_puntos_indi):
    id_os = gdf_puntos_indi.iloc[0]['id_os']
    codigo_ca = gdf_puntos_indi.iloc[0]['cod_ca']
    nombre_ca = gdf_puntos_indi.iloc[0]['nom_ca']
    semana_plan = gdf_puntos_indi.iloc[0]['semana_plan']
    
    # SELECCIONAR LOS LOTES DE SIEMBRAS
    # identifoca los lotes que se intersectan
    gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')
    # filtra los lotes intersectados en la capa original
    poligonos_intersect_siem = gdf_siembras.loc[gdf_siembras.index.isin(gdf_lotes_siem.index)]
    # copy
    poligonos_intersect_siem = poligonos_intersect_siem.copy()
    # agregar campo de semana_planificacion
    poligonos_intersect_siem['os'] = id_os
    # crea el campo soca, y coloca 0 o 1 dependiendo del origen
    poligonos_intersect_siem['soca'] = poligonos_intersect_siem['origen'].apply(lambda x: 1 if 'SIEMBRA 2024' in x else 0)

    # agrega los campos faltantes
    poligonos_intersect_siem['semana_plan'] = semana_plan
    
    # ordena los campos
    poligonos_intersect_siem = poligonos_intersect_siem[['unidad_01', 'unidad_02', 'unidad_03', 'unidad_04', 'unidad_05', 'area', 'soca', 'inst',
           'geom', 'origen', 'dias', 'fecha', 'os', 'semana_plan']]
    return poligonos_intersect_siem

def agregar_campos_faltantes(gdf_plan):
    gdf_plan['producto'] = ''
    gdf_plan['dosis'] = 0.0
    gdf_plan['id_labor'] = ''
    gdf_plan['fecha'] = ''
    gdf_plan['semana'] = 0
    gdf_plan['num_lib'] = 0
    gdf_plan['hora_ini'] = ''
    gdf_plan['hora_fin'] = ''
    gdf_plan['temp'] = 0
    gdf_plan['viento'] = 0
    gdf_plan['humedad'] = 0
    gdf_plan['cod_dron'] = ''
    gdf_plan['piloto_1'] = ''
    gdf_plan['piloto_2'] = ''
    gdf_plan['obs'] = ''
    gdf_plan['id_log'] = 0
    return gdf_plan

def convertir_a_multipolygon(geometry):
    if isinstance(geometry, Polygon):
        return MultiPolygon([geometry])
    return geometry

def convertir_a_wkb(polygon):
    wkb_data = wkb.dumps(polygon, hex=True)
    return wkb_data

def cargar_a_amigocloud(gdf):
    # repreyectar a WGS84
    gdf_pla_gral = gdf.to_crs(epsg=4326)
    # convertir poligonos a multipoligonos
    gdf_pla_gral['geom'] = gdf_pla_gral['geom'].apply(convertir_a_multipolygon)
    
    gdf_pla_gral['unidad_01'] = gdf_pla_gral['unidad_01'].astype(int)
    gdf_pla_gral['unidad_03'] = gdf_pla_gral['unidad_03'].astype(int)
    gdf_pla_gral['dias'] = gdf_pla_gral['dias'].astype(int)
    gdf_pla_gral['os'] = gdf_pla_gral['os'].astype(int)
    gdf_pla_gral['soca'] = gdf_pla_gral['soca'].astype(int)
    gdf_pla_gral['id'] = gdf_pla_gral['id'].astype(int)
    gdf_pla_gral['inst'] = gdf_pla_gral['inst'].astype(int)
    gdf_pla_gral['semana_plan'] = gdf_pla_gral['semana_plan'].astype(int)
    
    # recorrer el gdf de lotes y cargarlo a amigocloud
    id_proyecto = 33457
    for index, row in gdf_pla_gral.iterrows():
        wkb_hex = convertir_a_wkb(row['geom'])
        insert_sql = f"""
            INSERT INTO dataset_345601 (id, unidad_01, unidad_02, unidad_03, unidad_04, unidad_05, area, origen, dias, os, etiqueta, producto, dosis, cantidad, semana_plan, geometry)
            VALUES ({row['id']}, {row['unidad_01']}, '{row['unidad_02']}', {row['unidad_03']}, '{row['unidad_04']}', '{row['unidad_05']}', {row['area']}, '{row['origen']}', '{row['dias']}', '{row['os']}', '{str(round(row['area'],2)) + 'ha - ' + str(round(row['producto_cantidad'],2)) + 'ml'}', '{row['producto_plan']}', {row['producto_dosis']}, {row['producto_cantidad']}, {row['semana_plan']}, ST_SetSRID(ST_GeomFromWKB('\\x{wkb_hex}'), 4326));
            """
        query_sql = {'query': insert_sql}
        print('⚠️ Inicio proceso Lotes ID:', row['id'])
        resultado_post = amigocloud.ejecutar_query_sql(id_proyecto, insert_sql, 'post')
        marcar_como_planificado(row['id'])
        print('⚠️Fin proceso Lotes ID:', row['id'])
    return None

def cargar_a_amigocloud_semana_siguiente(gdf):
    # repreyectar a WGS84
    gdf_pla_gral = gdf.to_crs(epsg=4326)
    # convertir poligonos a multipoligonos
    gdf_pla_gral['geom'] = gdf_pla_gral['geom'].apply(convertir_a_multipolygon)
    
    gdf_pla_gral['unidad_01'] = gdf_pla_gral['unidad_01'].astype(int)
    gdf_pla_gral['unidad_03'] = gdf_pla_gral['unidad_03'].astype(int)
    gdf_pla_gral['dias'] = gdf_pla_gral['dias'].astype(int)
    gdf_pla_gral['os'] = gdf_pla_gral['os'].astype(int)
    gdf_pla_gral['soca'] = gdf_pla_gral['soca'].astype(int)
    gdf_pla_gral['id'] = gdf_pla_gral['id'].astype(int)
    gdf_pla_gral['inst'] = gdf_pla_gral['inst'].astype(int)
    
    
    # recorrer el gdf de lotes y cargarlo a amigocloud
    id_proyecto = 33457
    for index, row in gdf_pla_gral.iterrows():
        wkb_hex = convertir_a_wkb(row['geom'])
        insert_sql = f"""
            INSERT INTO dataset_381625 (id, unidad_01, unidad_02, unidad_03, unidad_04, unidad_05, area, origen, dias, os, etiqueta, producto, dosis, cantidad, semana_plan, geometry)
            VALUES ({row['id']}, {row['unidad_01']}, '{row['unidad_02']}', {row['unidad_03']}, '{row['unidad_04']}', '{row['unidad_05']}', {row['area']}, '{row['origen']}', '{row['dias']}', '{row['os']}', '{str(round(row['area'],2)) + 'ha - ' + str(round(row['producto_cantidad'],2)) + 'ml'}', '{row['producto_plan']}', {row['producto_dosis']}, {row['producto_cantidad']}, {row['semana_plan']}, ST_SetSRID(ST_GeomFromWKB('\\x{wkb_hex}'), 4326));
            """
        query_sql = {'query': insert_sql}
        resultado_post = amigocloud.ejecutar_query_sql(id_proyecto, insert_sql, 'post')
        print(f"Lotes cargado proxima semana ID: {row['id']}")
        # marcar_como_planificado(row['id'])
    return None

def cargar_a_amigocloud_lista_canhero_notif(gdf):
    # recorrer el gdf de lotes y cargarlo a amigocloud
    id_proyecto = 33457
    for index, row in gdf.iterrows():
        cod = row['unidad_03']
        nom = row['unidad_04']
        cod_canhero = str(cod) + ' / ' + nom
        insert_sql = f"insert into dataset_354656 (cod_canhero) values('{cod_canhero}')"
        query_sql = {'query': insert_sql}
        resultado_post = amigocloud.ejecutar_query_sql(id_proyecto, insert_sql, 'post')
        print(f"Se ha registrado nuevo cañero para notificacion: {cod_canhero}")
        # marcar_como_planificado(row['id'])
    return None

# verifica si en la dataframe existen nombres de lotes repetidos
def validar_lotes_repetidos(gdf_plan):
    cods_props = list(set(gdf_plan['unidad_01']))
    for i in cods_props:
        prop = gdf_plan[gdf_plan['unidad_01'] == i]
        dup = prop[prop['unidad_05'].duplicated(keep=False)]
        if prop['unidad_05'].duplicated().any():
            print('Lotes repedidos:', list(set(dup['unidad_05'])))
            return True
        else:
            return False
    return None

def crear_kmls(gdf_lotes):
    lista_cods = list(set(gdf_lotes['unidad_01']))
    for i in lista_cods:
        prop = gdf_lotes[gdf_lotes['unidad_01'] == i]
        prop_wgs = prop.to_crs(epsg=4326)
        output_folder = PATH_KML + '\\' + str(i)
        print(output_folder)
        
        if os.path.exists(output_folder):
            shutil.rmtree(output_folder)  # Elimina toda la carpeta y su contenido
        os.makedirs(output_folder)  # La vuelve a crear vacía
        
        # Recorrer el GeoDataFrame
        for idx, row in prop_wgs.iterrows():
            # Crear un nuevo documento KML
            kml_doc = simplekml.Kml()
            # Obtener el polígono y el nombre
            polygon = row['geom']
            name = row['unidad_05']
            # Convertir el polígono en una lista de coordenadas
            if polygon.geom_type == "Polygon":
                coords = [(x, y) for x, y in zip(*polygon.exterior.xy)]
            elif polygon.geom_type == "MultiPolygon":
            # puedes iterar si quieres más de uno, aquí tomamos el primero
                first_poly = list(polygon.geoms)[0]
                coords = [(x, y) for x, y in zip(*first_poly.exterior.xy)]
            else:
                print(f"❌ Geometría no compatible: {polygon.geom_type}")
                continue  # salta este registro
            # Añadir el polígono al documento KML
            pol = kml_doc.newpolygon(name=name, outerboundaryis=coords)
            # Guardar el archivo KML
            file_name = f"{name}.kml"
            output_path = os.path.join(output_folder, file_name)
            kml_doc.save(output_path)
    return None

In [31]:
amigocloud = AmigocloudFunctions(token=API_AMIGOCLOUD_TOKEN_ADM)
amigocloud

# ACTUALIZAR SHP PLANIFICACION

In [32]:
gdf_siembras = get_siembras()
gdf_cat = get_catastro()

In [33]:
gdf_puntos = obtener_planificacion_no_procesado()

In [34]:
gdf_puntos

,id_os,geom,cod_ca,nom_ca,obs,procesado,producto,dosis,semana_plan
0,1162,"MULTIPOINT (489025.955 8105210.369, 489024.132...",9722,OLGUIN FLORES MIGUELINA,None,False,crisopa,3.0,41
1,1163,MULTIPOINT (470850.688 8124352.367),4915,GUZMAN YOLANDA COCA UREY DE,None,False,crisopa,3.0,41
2,1164,"MULTIPOINT (484493.284 8105398.773, 484529.428...",3408,ESPINOZA TERRAZAS MIGUEL,None,False,crisopa,3.0,41
3,1165,"MULTIPOINT (461598.917 8089308.672, 461741.706...",8842,MUÃOZ SUAREZ HUMBERTO,None,False,crisopa,3.0,41
4,1166,MULTIPOINT (483610.959 8080685.258),42666,PEREDO BRYEHEY MARCO ANTONIO,None,False,crisopa,3.0,41
5,1167,"MULTIPOINT (488088.816 8104937.425, 488022.053...",9722,OLGUIN FLORES MIGUELINA,None,False,crisopa,3.0,41
6,1168,"MULTIPOINT (469253.791 8099737.015, 469346.307...",40136,FAREL GUZMAN ANA MARIA,None,False,crisopa,3.0,41
7,1169,"MULTIPOINT (490553.864 8090317.617, 490780.760...",13123,RIC PARADA SALVADOR,None,False,crisopa,3.0,41
8,1170,"MULTIPOINT (464720.606 8101191.903, 464769.262...",1970,CIRBIAN BARROS ROBERT,None,False,crisopa,3.0,41
9,1171,"MULTIPOINT (462140.698 8083310.486, 461977.153...",18027,AGUILERA TARRADELLES GUILLERMO,None,False,crisopa,3.0,41
10,1172,"MULTIPOINT (494917.361 8109589.907, 493031.157...",12174,ROJAS SILES GERBACIO RICHAR,None,False,crisopa,3.0,41
11,1173,"MULTIPOINT (480406.721 8087128.790, 483905.487...",805,AGROP. TRES HNOS DEL ORIENTE,None,False,crisopa,3.0,41
12,1174,MULTIPOINT (498408.846 8109469.973),7077,CKOLO ESCALERA CARLOS,None,False,crisopa,3.0,41
13,1175,"MULTIPOINT (471342.613 8121724.026, 471476.612...",40190,DURAN MERIDA CHARLES ROBERT,None,False,crisopa,3.0,41
14,1176,"MULTIPOINT (453955.556 8079509.087, 454446.586...",767,PROSER S.R.L,None,False,crisopa,3.0,41
15,1177,"MULTIPOINT (485217.064 8103109.012, 485099.375...",42446,BRUNNER SUAREZ JUAN CARLOS,None,False,crisopa,3.0,41
16,1142,"MULTIPOINT (517490.646 8070307.841, 519207.721...",41594,AGROPECUARIA CAMPO DULCE S.R.L.,None,False,crisopa,3.0,41
17,1143,"MULTIPOINT (522662.195 8076610.656, 523349.038...",42455,CIA IND. COMERCIAL HNOS. VICENTE S.R.L.,None,False,crisopa,3.0,41
18,1144,"MULTIPOINT (430175.592 8091356.932, 430310.770...",12308,ROCA CHAVEZ MAURICIO DANIEL,None,False,crisopa,3.0,41
19,1145,"MULTIPOINT (458630.225 8101153.644, 460491.791...",2899,EGUEZ ELHAGE JOSE EDUARDO,None,False,crisopa,3.0,41
20,1147,"MULTIPOINT (473328.372 8076480.409, 472639.337...",2641,CRONENBOLD AGUILERA ROBERTO,None,False,crisopa,3.0,41
21,1148,"MULTIPOINT (482546.716 8090278.618, 482177.007...",388,AGROPECUARIA MARIANA S.R.L.,None,False,crisopa,3.0,41
22,1150,"MULTIPOINT (467019.101 8086344.394, 467192.824...",3323,TREPP CARRASCO RUDIGER,None,False,crisopa,3.0,41
23,1151,"MULTIPOINT (484909.905 8073641.570, 484846.699...",2641,CRONENBOLD AGUILERA ROBERTO,None,False,crisopa,3.0,41
24,1152,"MULTIPOINT (487235.665 8102246.840, 486669.100...",42231,PAZ FERNANDEZ RODRIGO,None,False,crisopa,3.0,41
25,1153,"MULTIPOINT (481280.762 8078751.436, 481457.777...",2641,CRONENBOLD AGUILERA ROBERTO,None,False,crisopa,3.0,41
26,1154,"MULTIPOINT (468473.569 8093022.853, 468008.243...",13067,SAUCEDO CERRUTI SONIA,None,False,crisopa,3.0,41
27,1155,"MULTIPOINT (454374.106 8078058.941, 454589.184...",4914,GONZALEZ LIMPIAS LUIS ALBERTO,None,False,crisopa,3.0,41
28,1156,"MULTIPOINT (475282.602 8093163.354, 474697.255...",794,AGUILERA WENDE MARIANO,None,False,crisopa,3.0,41
29,1158,"MULTIPOINT (494051.638 8099406.541, 493443.446...",42023,RODRIGUEZ ROJAS HUGO ALVARO,None,False,crisopa,3.0,41
30,1159,MULTIPOINT (491968.679 8129595.656),9930,OJEDA GARCIA MIGUEL,None,False,crisopa,3.0,41
31,1160,"MULTIPOINT (492996.491 8088705.540, 493125.578...",86,AGUILERA TARADELLES JOSE LUIS,None,False,crisopa,3.0,41
32,1161,"MULTIPOINT (474523.767 8099274.968, 474725.198...",4061,FRITZER PAZ ROMEL,None,False,crisopa,3.0,41
33,1179,MULTIPOINT (489932.010 8100295.860),2161,CORDOVA CAMARA LUCIO,None,False,crisopa,3.0,41
34,1180,"MULTIPOINT (486642.117 8073243.084, 486459.401...",42441,JUAN CARLOS ORTIZ BANZER \n,None,False,crisopa,3.0,41
35,1181,MULTIPOINT (493147.363 8095206.598),2522,CARO SONIA GENOVEVA CLAROS DE,None,False,crisopa,3.0,41
36,1146,"MULTIPOINT (460484.061 8095850.109, 463515.523...",41970,ROCA LANDIVAR ARMANDO,None,False,crisopa,3.0,41

In [35]:
for i, row in gdf_puntos.iterrows():
    ors = row['id_os']
    produc_plan = row['producto']
    produc_dosis = row['dosis']
    
    puntos = filtrar_os_y_quitar_caracteres(gdf_puntos, ors)
    multipoint_gdf = puntos.copy()
    puntos_individuales = crear_puntos_individuales(multipoint_gdf)
    
    lotes_solicidud = definir_lotes_solicitud(puntos_individuales)
    lotes_siembra = definir_lotes_siembra(puntos_individuales)
    
    # verificar si algun dataframe esta vacio
    dfs = [df for df in [lotes_solicidud, lotes_siembra] if not df.empty]
    # concatena los dfs no vacios
    concat_plan = pd.concat(dfs, axis=0, ignore_index=True)
    
    plan = agregar_campos_faltantes(concat_plan)
    #RECALCULAR EL AREA
    plan['area'] = plan.geom.area / 10000

    plan['producto_plan'] = produc_plan
    plan['producto_dosis'] = produc_dosis
    plan['producto_cantidad'] = plan['area'] * plan['producto_dosis']
    
    #plan.rename(columns={'geom': 'geom'}, inplace=True)
    #plan = plan.set_geometry("geom")
    plan['unidad_01'] = plan['unidad_01'].astype(int)
    plan['unidad_03'] = plan['unidad_03'].astype(int)
    plan['dias'] = plan['dias'].astype(int)
    plan['os'] = plan['os'].astype(int)
    plan['soca'] = plan['soca'].astype(int)
    plan['inst'] = plan['inst'].astype(int)

    # validas que la planificacion no tenga lotes con el mismo nombre
    if validar_lotes_repetidos(plan):
        print(f"ERROR: Existen lotes con nombre repetido en la propiedad: {plan.iloc[0]['unidad_01']}")
        continue
    #crear_kmls(plan)    
    plan.to_postgis("parte_diario_ctrl_bio", obtener_engine(), schema="drones_control_bio", if_exists="append")
    
    marcar_como_procesado(ors)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1162 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1163 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1164 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1165 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1166 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1167 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1168 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1169 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1170 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1171 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1172 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1173 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1174 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1175 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1176 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1177 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1142 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1143 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1144 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1145 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1147 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1148 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1150 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1151 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1152 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1153 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1154 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1155 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1156 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1158 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1159 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1160 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1161 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1179 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1180 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1181 marcado como procesado.

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3804\3984149257.py:181: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:32720

  gdf_lotes_siem = gpd.sjoin(gdf_siembras, gdf_puntos_indi, how='inner', predicate='intersects')

✔️ id_os 1146 marcado como procesado.

## Cargar a AmigoCloud los lotes sin planificar

In [36]:
lotes_sin_planificar = obtener_parte_diario_sin_planificar()
print('Lotes sin planificar:', len(lotes_sin_planificar))

Lotes sin planificar: 221

In [38]:
lotes_sin_planificar['area'].sum()

2804.2198011032397

In [39]:
cargar_a_amigocloud(lotes_sin_planificar)

⚠️ Inicio proceso Lotes ID: 7527
✔️ id_lote 7527 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7527
⚠️ Inicio proceso Lotes ID: 7528
✔️ id_lote 7528 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7528
⚠️ Inicio proceso Lotes ID: 7529
✔️ id_lote 7529 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7529
⚠️ Inicio proceso Lotes ID: 7530
✔️ id_lote 7530 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7530
⚠️ Inicio proceso Lotes ID: 7531
✔️ id_lote 7531 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7531
⚠️ Inicio proceso Lotes ID: 7532
✔️ id_lote 7532 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7532
⚠️ Inicio proceso Lotes ID: 7533
✔️ id_lote 7533 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7533
⚠️ Inicio proceso Lotes ID: 7534
✔️ id_lote 7534 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7534
⚠️ Inicio proceso Lotes ID: 7535
✔️ id_lote 7535 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7535
⚠️ Inicio proceso Lotes ID: 7536
✔️ id_lote 7536 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7536
⚠️ Inicio proceso Lotes ID: 7537
✔️ id_lote 7537 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7537
⚠️ Inicio proceso Lotes ID: 7538
✔️ id_lote 7538 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7538
⚠️ Inicio proceso Lotes ID: 7539
✔️ id_lote 7539 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7539
⚠️ Inicio proceso Lotes ID: 7540
✔️ id_lote 7540 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7540
⚠️ Inicio proceso Lotes ID: 7541
✔️ id_lote 7541 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7541
⚠️ Inicio proceso Lotes ID: 7542
✔️ id_lote 7542 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7542
⚠️ Inicio proceso Lotes ID: 7543
✔️ id_lote 7543 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7543
⚠️ Inicio proceso Lotes ID: 7544
✔️ id_lote 7544 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7544
⚠️ Inicio proceso Lotes ID: 7545
✔️ id_lote 7545 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7545
⚠️ Inicio proceso Lotes ID: 7546
✔️ id_lote 7546 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7546
⚠️ Inicio proceso Lotes ID: 7547
✔️ id_lote 7547 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7547
⚠️ Inicio proceso Lotes ID: 7548
✔️ id_lote 7548 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7548
⚠️ Inicio proceso Lotes ID: 7549
✔️ id_lote 7549 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7549
⚠️ Inicio proceso Lotes ID: 7550
✔️ id_lote 7550 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7550
⚠️ Inicio proceso Lotes ID: 7551
✔️ id_lote 7551 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7551
⚠️ Inicio proceso Lotes ID: 7552
✔️ id_lote 7552 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7552
⚠️ Inicio proceso Lotes ID: 7553
✔️ id_lote 7553 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7553
⚠️ Inicio proceso Lotes ID: 7554
✔️ id_lote 7554 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7554
⚠️ Inicio proceso Lotes ID: 7555
✔️ id_lote 7555 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7555
⚠️ Inicio proceso Lotes ID: 7556
✔️ id_lote 7556 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7556
⚠️ Inicio proceso Lotes ID: 7557
✔️ id_lote 7557 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7557
⚠️ Inicio proceso Lotes ID: 7558
✔️ id_lote 7558 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7558
⚠️ Inicio proceso Lotes ID: 7559
✔️ id_lote 7559 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7559
⚠️ Inicio proceso Lotes ID: 7560
✔️ id_lote 7560 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7560
⚠️ Inicio proceso Lotes ID: 7561
✔️ id_lote 7561 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7561
⚠️ Inicio proceso Lotes ID: 7562
✔️ id_lote 7562 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7562
⚠️ Inicio proceso Lotes ID: 7563
✔️ id_lote 7563 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7563
⚠️ Inicio proceso Lotes ID: 7564
✔️ id_lote 7564 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7564
⚠️ Inicio proceso Lotes ID: 7565
✔️ id_lote 7565 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7565
⚠️ Inicio proceso Lotes ID: 7566
✔️ id_lote 7566 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7566
⚠️ Inicio proceso Lotes ID: 7567
✔️ id_lote 7567 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7567
⚠️ Inicio proceso Lotes ID: 7568
✔️ id_lote 7568 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7568
⚠️ Inicio proceso Lotes ID: 7569
✔️ id_lote 7569 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7569
⚠️ Inicio proceso Lotes ID: 7570
✔️ id_lote 7570 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7570
⚠️ Inicio proceso Lotes ID: 7571
✔️ id_lote 7571 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7571
⚠️ Inicio proceso Lotes ID: 7572
✔️ id_lote 7572 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7572
⚠️ Inicio proceso Lotes ID: 7573
✔️ id_lote 7573 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7573
⚠️ Inicio proceso Lotes ID: 7574
✔️ id_lote 7574 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7574
⚠️ Inicio proceso Lotes ID: 7575
✔️ id_lote 7575 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7575
⚠️ Inicio proceso Lotes ID: 7576
✔️ id_lote 7576 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7576
⚠️ Inicio proceso Lotes ID: 7577
✔️ id_lote 7577 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7577
⚠️ Inicio proceso Lotes ID: 7578
✔️ id_lote 7578 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7578
⚠️ Inicio proceso Lotes ID: 7579
✔️ id_lote 7579 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7579
⚠️ Inicio proceso Lotes ID: 7580
✔️ id_lote 7580 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7580
⚠️ Inicio proceso Lotes ID: 7581
✔️ id_lote 7581 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7581
⚠️ Inicio proceso Lotes ID: 7582
✔️ id_lote 7582 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7582
⚠️ Inicio proceso Lotes ID: 7583
✔️ id_lote 7583 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7583
⚠️ Inicio proceso Lotes ID: 7584
✔️ id_lote 7584 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7584
⚠️ Inicio proceso Lotes ID: 7585
✔️ id_lote 7585 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7585
⚠️ Inicio proceso Lotes ID: 7586
✔️ id_lote 7586 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7586
⚠️ Inicio proceso Lotes ID: 7587
✔️ id_lote 7587 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7587
⚠️ Inicio proceso Lotes ID: 7588
✔️ id_lote 7588 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7588
⚠️ Inicio proceso Lotes ID: 7589
✔️ id_lote 7589 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7589
⚠️ Inicio proceso Lotes ID: 7590
✔️ id_lote 7590 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7590
⚠️ Inicio proceso Lotes ID: 7591
✔️ id_lote 7591 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7591
⚠️ Inicio proceso Lotes ID: 7592
✔️ id_lote 7592 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7592
⚠️ Inicio proceso Lotes ID: 7593
✔️ id_lote 7593 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7593
⚠️ Inicio proceso Lotes ID: 7594
✔️ id_lote 7594 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7594
⚠️ Inicio proceso Lotes ID: 7595
✔️ id_lote 7595 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7595
⚠️ Inicio proceso Lotes ID: 7596
✔️ id_lote 7596 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7596
⚠️ Inicio proceso Lotes ID: 7597
✔️ id_lote 7597 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7597
⚠️ Inicio proceso Lotes ID: 7598
✔️ id_lote 7598 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7598
⚠️ Inicio proceso Lotes ID: 7599
✔️ id_lote 7599 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7599
⚠️ Inicio proceso Lotes ID: 7600
✔️ id_lote 7600 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7600
⚠️ Inicio proceso Lotes ID: 7601
✔️ id_lote 7601 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7601
⚠️ Inicio proceso Lotes ID: 7602
✔️ id_lote 7602 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7602
⚠️ Inicio proceso Lotes ID: 7603
✔️ id_lote 7603 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7603
⚠️ Inicio proceso Lotes ID: 7604
✔️ id_lote 7604 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7604
⚠️ Inicio proceso Lotes ID: 7605
✔️ id_lote 7605 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7605
⚠️ Inicio proceso Lotes ID: 7606
✔️ id_lote 7606 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7606
⚠️ Inicio proceso Lotes ID: 7607
✔️ id_lote 7607 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7607
⚠️ Inicio proceso Lotes ID: 7608
✔️ id_lote 7608 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7608
⚠️ Inicio proceso Lotes ID: 7609
✔️ id_lote 7609 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7609
⚠️ Inicio proceso Lotes ID: 7610
✔️ id_lote 7610 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7610
⚠️ Inicio proceso Lotes ID: 7611
✔️ id_lote 7611 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7611
⚠️ Inicio proceso Lotes ID: 7612
✔️ id_lote 7612 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7612
⚠️ Inicio proceso Lotes ID: 7613
✔️ id_lote 7613 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7613
⚠️ Inicio proceso Lotes ID: 7614
✔️ id_lote 7614 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7614
⚠️ Inicio proceso Lotes ID: 7615
✔️ id_lote 7615 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7615
⚠️ Inicio proceso Lotes ID: 7616
✔️ id_lote 7616 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7616
⚠️ Inicio proceso Lotes ID: 7617
✔️ id_lote 7617 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7617
⚠️ Inicio proceso Lotes ID: 7618
✔️ id_lote 7618 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7618
⚠️ Inicio proceso Lotes ID: 7619
✔️ id_lote 7619 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7619
⚠️ Inicio proceso Lotes ID: 7620
✔️ id_lote 7620 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7620
⚠️ Inicio proceso Lotes ID: 7621
✔️ id_lote 7621 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7621
⚠️ Inicio proceso Lotes ID: 7622
✔️ id_lote 7622 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7622
⚠️ Inicio proceso Lotes ID: 7623
✔️ id_lote 7623 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7623
⚠️ Inicio proceso Lotes ID: 7624
✔️ id_lote 7624 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7624
⚠️ Inicio proceso Lotes ID: 7625
✔️ id_lote 7625 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7625
⚠️ Inicio proceso Lotes ID: 7626
✔️ id_lote 7626 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7626
⚠️ Inicio proceso Lotes ID: 7627
✔️ id_lote 7627 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7627
⚠️ Inicio proceso Lotes ID: 7628
✔️ id_lote 7628 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7628
⚠️ Inicio proceso Lotes ID: 7629
✔️ id_lote 7629 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7629
⚠️ Inicio proceso Lotes ID: 7630
✔️ id_lote 7630 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7630
⚠️ Inicio proceso Lotes ID: 7631
✔️ id_lote 7631 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7631
⚠️ Inicio proceso Lotes ID: 7632
✔️ id_lote 7632 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7632
⚠️ Inicio proceso Lotes ID: 7633
✔️ id_lote 7633 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7633
⚠️ Inicio proceso Lotes ID: 7634
✔️ id_lote 7634 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7634
⚠️ Inicio proceso Lotes ID: 7635
✔️ id_lote 7635 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7635
⚠️ Inicio proceso Lotes ID: 7636
✔️ id_lote 7636 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7636
⚠️ Inicio proceso Lotes ID: 7637
✔️ id_lote 7637 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7637
⚠️ Inicio proceso Lotes ID: 7638
✔️ id_lote 7638 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7638
⚠️ Inicio proceso Lotes ID: 7639
✔️ id_lote 7639 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7639
⚠️ Inicio proceso Lotes ID: 7640
✔️ id_lote 7640 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7640
⚠️ Inicio proceso Lotes ID: 7641
✔️ id_lote 7641 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7641
⚠️ Inicio proceso Lotes ID: 7642
✔️ id_lote 7642 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7642
⚠️ Inicio proceso Lotes ID: 7643
✔️ id_lote 7643 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7643
⚠️ Inicio proceso Lotes ID: 7644
✔️ id_lote 7644 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7644
⚠️ Inicio proceso Lotes ID: 7645
✔️ id_lote 7645 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7645
⚠️ Inicio proceso Lotes ID: 7646
✔️ id_lote 7646 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7646
⚠️ Inicio proceso Lotes ID: 7647
✔️ id_lote 7647 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7647
⚠️ Inicio proceso Lotes ID: 7648
✔️ id_lote 7648 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7648
⚠️ Inicio proceso Lotes ID: 7649
✔️ id_lote 7649 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7649
⚠️ Inicio proceso Lotes ID: 7650
✔️ id_lote 7650 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7650
⚠️ Inicio proceso Lotes ID: 7651
✔️ id_lote 7651 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7651
⚠️ Inicio proceso Lotes ID: 7652
✔️ id_lote 7652 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7652
⚠️ Inicio proceso Lotes ID: 7653
✔️ id_lote 7653 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7653
⚠️ Inicio proceso Lotes ID: 7654
✔️ id_lote 7654 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7654
⚠️ Inicio proceso Lotes ID: 7655
✔️ id_lote 7655 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7655
⚠️ Inicio proceso Lotes ID: 7656
✔️ id_lote 7656 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7656
⚠️ Inicio proceso Lotes ID: 7657
✔️ id_lote 7657 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7657
⚠️ Inicio proceso Lotes ID: 7658
✔️ id_lote 7658 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7658
⚠️ Inicio proceso Lotes ID: 7659
✔️ id_lote 7659 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7659
⚠️ Inicio proceso Lotes ID: 7660
✔️ id_lote 7660 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7660
⚠️ Inicio proceso Lotes ID: 7661
✔️ id_lote 7661 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7661
⚠️ Inicio proceso Lotes ID: 7662
✔️ id_lote 7662 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7662
⚠️ Inicio proceso Lotes ID: 7663
✔️ id_lote 7663 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7663
⚠️ Inicio proceso Lotes ID: 7664
✔️ id_lote 7664 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7664
⚠️ Inicio proceso Lotes ID: 7665
✔️ id_lote 7665 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7665
⚠️ Inicio proceso Lotes ID: 7666
✔️ id_lote 7666 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7666
⚠️ Inicio proceso Lotes ID: 7667
✔️ id_lote 7667 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7667
⚠️ Inicio proceso Lotes ID: 7668
✔️ id_lote 7668 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7668
⚠️ Inicio proceso Lotes ID: 7669
✔️ id_lote 7669 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7669
⚠️ Inicio proceso Lotes ID: 7670
✔️ id_lote 7670 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7670
⚠️ Inicio proceso Lotes ID: 7671
✔️ id_lote 7671 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7671
⚠️ Inicio proceso Lotes ID: 7672
✔️ id_lote 7672 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7672
⚠️ Inicio proceso Lotes ID: 7673
✔️ id_lote 7673 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7673
⚠️ Inicio proceso Lotes ID: 7674
✔️ id_lote 7674 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7674
⚠️ Inicio proceso Lotes ID: 7675
✔️ id_lote 7675 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7675
⚠️ Inicio proceso Lotes ID: 7676
✔️ id_lote 7676 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7676
⚠️ Inicio proceso Lotes ID: 7677
✔️ id_lote 7677 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7677
⚠️ Inicio proceso Lotes ID: 7678
✔️ id_lote 7678 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7678
⚠️ Inicio proceso Lotes ID: 7679
✔️ id_lote 7679 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7679
⚠️ Inicio proceso Lotes ID: 7680
✔️ id_lote 7680 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7680
⚠️ Inicio proceso Lotes ID: 7681
✔️ id_lote 7681 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7681
⚠️ Inicio proceso Lotes ID: 7682
✔️ id_lote 7682 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7682
⚠️ Inicio proceso Lotes ID: 7683
✔️ id_lote 7683 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7683
⚠️ Inicio proceso Lotes ID: 7684
✔️ id_lote 7684 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7684
⚠️ Inicio proceso Lotes ID: 7685
✔️ id_lote 7685 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7685
⚠️ Inicio proceso Lotes ID: 7686
✔️ id_lote 7686 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7686
⚠️ Inicio proceso Lotes ID: 7687
✔️ id_lote 7687 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7687
⚠️ Inicio proceso Lotes ID: 7688
✔️ id_lote 7688 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7688
⚠️ Inicio proceso Lotes ID: 7689
✔️ id_lote 7689 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7689
⚠️ Inicio proceso Lotes ID: 7690
✔️ id_lote 7690 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7690
⚠️ Inicio proceso Lotes ID: 7691
✔️ id_lote 7691 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7691
⚠️ Inicio proceso Lotes ID: 7692
✔️ id_lote 7692 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7692
⚠️ Inicio proceso Lotes ID: 7693
✔️ id_lote 7693 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7693
⚠️ Inicio proceso Lotes ID: 7694
✔️ id_lote 7694 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7694
⚠️ Inicio proceso Lotes ID: 7695
✔️ id_lote 7695 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7695
⚠️ Inicio proceso Lotes ID: 7696
✔️ id_lote 7696 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7696
⚠️ Inicio proceso Lotes ID: 7697
✔️ id_lote 7697 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7697
⚠️ Inicio proceso Lotes ID: 7698
✔️ id_lote 7698 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7698
⚠️ Inicio proceso Lotes ID: 7699
✔️ id_lote 7699 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7699
⚠️ Inicio proceso Lotes ID: 7700
✔️ id_lote 7700 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7700
⚠️ Inicio proceso Lotes ID: 7701
✔️ id_lote 7701 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7701
⚠️ Inicio proceso Lotes ID: 7702
✔️ id_lote 7702 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7702
⚠️ Inicio proceso Lotes ID: 7703
✔️ id_lote 7703 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7703
⚠️ Inicio proceso Lotes ID: 7704
✔️ id_lote 7704 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7704
⚠️ Inicio proceso Lotes ID: 7705
✔️ id_lote 7705 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7705
⚠️ Inicio proceso Lotes ID: 7706
✔️ id_lote 7706 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7706
⚠️ Inicio proceso Lotes ID: 7707
✔️ id_lote 7707 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7707
⚠️ Inicio proceso Lotes ID: 7708
✔️ id_lote 7708 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7708
⚠️ Inicio proceso Lotes ID: 7709
✔️ id_lote 7709 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7709
⚠️ Inicio proceso Lotes ID: 7710
✔️ id_lote 7710 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7710
⚠️ Inicio proceso Lotes ID: 7711
✔️ id_lote 7711 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7711
⚠️ Inicio proceso Lotes ID: 7712
✔️ id_lote 7712 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7712
⚠️ Inicio proceso Lotes ID: 7713
✔️ id_lote 7713 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7713
⚠️ Inicio proceso Lotes ID: 7714
✔️ id_lote 7714 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7714
⚠️ Inicio proceso Lotes ID: 7715
✔️ id_lote 7715 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7715
⚠️ Inicio proceso Lotes ID: 7716
✔️ id_lote 7716 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7716
⚠️ Inicio proceso Lotes ID: 7717
✔️ id_lote 7717 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7717
⚠️ Inicio proceso Lotes ID: 7718
✔️ id_lote 7718 marcado como PLANIFICADO.
⚠️Fin proceso Lotes ID: 7718

In [40]:
lotes_planificados = obtener_parte_diario_planificado()

In [41]:
lotes_planificados["area"].sum()

4313.4286250626965

In [42]:
lotes_planificados = obtener_parte_diario_planificado()
lotes_planificados = lotes_planificados[['unidad_03', 'unidad_04']]
lotes_planificados = lotes_planificados.drop_duplicates(subset=['unidad_03'])
lotes_planificados

     unidad_03                                unidad_04
0          388              AGROPECUARIA MARIANA S.R.L.
9        17680               BALDELOMAR HIDALGO JULIETA
10        2030           COLAMARINO DI SILVIO ANTONIETA
11         765                     AGROP. CATALA S.R.L.
23       42239                  CORDOVA OLGUIN LEONARDO
50         805             AGROP. TRES HNOS DEL ORIENTE
55         633              AGROP. VICENTE ROCA GIL SRL
67       15195                 VEIZAGA ENRIQUEZ GUSTAVO
68       42740                     MORENO PARADA JULIAN
76       41819               AGROPECUARIA GUSTAVITO SRL
87       11805                RIOJA CABRERA JOSE GROVER
89       15162               VELASCO ANEZ MARCO ANTONIO
94       12075                     ROJAS GONZALES TOMAS
96        1741                  CARO ALTAMIRANO ROSARIO
99        5011                    FRANCO ARIAS GREGORIO
104       4915              GUZMAN YOLANDA COCA UREY DE
106        692                      AMURRIO TAPIA JAIME
108      30907              ALVAREZ FUENTES JUAN CARLOS
112      13763               TUFINO SCHWENK RUBEN DARIO
116       4882                    GUZMAN MONTANO WILSON
121      17678                  ESPINOZA JUANA MAIDA DE
127       5001                    GUZMAN CACERES ROXANA
132      11860                     ROCA SERRANO ARMANDO
139      14744                 VARGAS FAUSTINA PINTO DE
152       9677             OVANDO JIMENEZ JAIRO ESTEVAN
173      20180                LINARES SALVATIERRA DAVID
180       9722                  OLGUIN FLORES MIGUELINA
187       3408                 ESPINOZA TERRAZAS MIGUEL
190       8842                   MUÃOZ SUAREZ HUMBERTO
198      42666             PEREDO BRYEHEY MARCO ANTONIO
203      40136                   FAREL GUZMAN ANA MARIA
208      13123                      RIC PARADA SALVADOR
215       1970                    CIRBIAN BARROS ROBERT
219      18027           AGUILERA TARRADELLES GUILLERMO
221      12174              ROJAS SILES GERBACIO RICHAR
226       7077                    CKOLO ESCALERA CARLOS
227      40190              DURAN MERIDA CHARLES ROBERT
229        767                             PROSER S.R.L
233      42446               BRUNNER SUAREZ JUAN CARLOS
236      41594          AGROPECUARIA CAMPO DULCE S.R.L.
264      42455  CIA IND. COMERCIAL HNOS. VICENTE S.R.L.
284      12308              ROCA CHAVEZ MAURICIO DANIEL
298       2899                EGUEZ ELHAGE JOSE EDUARDO
305       2641              CRONENBOLD AGUILERA ROBERTO
329       3323                   TREPP CARRASCO RUDIGER
349      42231                    PAZ FERNANDEZ RODRIGO
357      13067                    SAUCEDO CERRUTI SONIA
360       4914            GONZALEZ LIMPIAS LUIS ALBERTO
365        794                   AGUILERA WENDE MARIANO
370      42023              RODRIGUEZ ROJAS HUGO ALVARO
373       9930                      OJEDA GARCIA MIGUEL
374         86            AGUILERA TARADELLES JOSE LUIS
378       4061                        FRITZER PAZ ROMEL
383       2161                     CORDOVA CAMARA LUCIO
384      42441                JUAN CARLOS ORTIZ BANZER
386       2522            CARO SONIA GENOVEVA CLAROS DE
387      41970                    ROCA LANDIVAR ARMANDO

In [43]:
cargar_a_amigocloud_lista_canhero_notif(lotes_planificados)

Se ha registrado nuevo cañero para notificacion: 388 / AGROPECUARIA MARIANA S.R.L.
Se ha registrado nuevo cañero para notificacion: 17680 / BALDELOMAR HIDALGO JULIETA
Se ha registrado nuevo cañero para notificacion: 2030 / COLAMARINO DI SILVIO ANTONIETA
Se ha registrado nuevo cañero para notificacion: 765 / AGROP. CATALA S.R.L.
Se ha registrado nuevo cañero para notificacion: 42239 / CORDOVA OLGUIN LEONARDO
Se ha registrado nuevo cañero para notificacion: 805 / AGROP. TRES HNOS DEL ORIENTE
Se ha registrado nuevo cañero para notificacion: 633 / AGROP. VICENTE ROCA GIL SRL
Se ha registrado nuevo cañero para notificacion: 15195 / VEIZAGA ENRIQUEZ GUSTAVO
Se ha registrado nuevo cañero para notificacion: 42740 / MORENO PARADA JULIAN
Se ha registrado nuevo cañero para notificacion: 41819 / AGROPECUARIA GUSTAVITO SRL
Se ha registrado nuevo cañero para notificacion: 11805 / RIOJA CABRERA JOSE GROVER
Se ha registrado nuevo cañero para notificacion: 15162 / VELASCO ANEZ MARCO ANTONIO
Se ha registrado nuevo cañero para notificacion: 12075 / ROJAS GONZALES TOMAS
Se ha registrado nuevo cañero para notificacion: 1741 / CARO ALTAMIRANO ROSARIO
Se ha registrado nuevo cañero para notificacion: 5011 / FRANCO ARIAS GREGORIO
Se ha registrado nuevo cañero para notificacion: 4915 / GUZMAN YOLANDA COCA UREY DE
Se ha registrado nuevo cañero para notificacion: 692 / AMURRIO TAPIA JAIME
Se ha registrado nuevo cañero para notificacion: 30907 / ALVAREZ FUENTES JUAN CARLOS
Se ha registrado nuevo cañero para notificacion: 13763 / TUFINO SCHWENK RUBEN DARIO
Se ha registrado nuevo cañero para notificacion: 4882 / GUZMAN MONTANO WILSON
Se ha registrado nuevo cañero para notificacion: 17678 / ESPINOZA JUANA MAIDA DE
Se ha registrado nuevo cañero para notificacion: 5001 / GUZMAN CACERES ROXANA
Se ha registrado nuevo cañero para notificacion: 11860 / ROCA SERRANO ARMANDO
Se ha registrado nuevo cañero para notificacion: 14744 / VARGAS FAUSTINA PINTO DE
Se ha registrado nuevo cañero para notificacion: 9677 / OVANDO JIMENEZ JAIRO ESTEVAN
Se ha registrado nuevo cañero para notificacion: 20180 / LINARES SALVATIERRA DAVID
Se ha registrado nuevo cañero para notificacion: 9722 / OLGUIN FLORES MIGUELINA
Se ha registrado nuevo cañero para notificacion: 3408 / ESPINOZA TERRAZAS MIGUEL
Se ha registrado nuevo cañero para notificacion: 8842 / MUÃOZ SUAREZ HUMBERTO
Se ha registrado nuevo cañero para notificacion: 42666 / PEREDO BRYEHEY MARCO ANTONIO
Se ha registrado nuevo cañero para notificacion: 40136 / FAREL GUZMAN ANA MARIA
Se ha registrado nuevo cañero para notificacion: 13123 / RIC PARADA SALVADOR
Se ha registrado nuevo cañero para notificacion: 1970 / CIRBIAN BARROS ROBERT
Se ha registrado nuevo cañero para notificacion: 18027 / AGUILERA TARRADELLES GUILLERMO
Se ha registrado nuevo cañero para notificacion: 12174 / ROJAS SILES GERBACIO RICHAR
Se ha registrado nuevo cañero para notificacion: 7077 / CKOLO ESCALERA CARLOS
Se ha registrado nuevo cañero para notificacion: 40190 / DURAN MERIDA CHARLES ROBERT
Se ha registrado nuevo cañero para notificacion: 767 / PROSER S.R.L
Se ha registrado nuevo cañero para notificacion: 42446 / BRUNNER SUAREZ JUAN CARLOS
Se ha registrado nuevo cañero para notificacion: 41594 / AGROPECUARIA CAMPO DULCE S.R.L.
Se ha registrado nuevo cañero para notificacion: 42455 / CIA IND. COMERCIAL HNOS. VICENTE S.R.L.
Se ha registrado nuevo cañero para notificacion: 12308 / ROCA CHAVEZ MAURICIO DANIEL
Se ha registrado nuevo cañero para notificacion: 2899 / EGUEZ ELHAGE JOSE EDUARDO
Se ha registrado nuevo cañero para notificacion: 2641 / CRONENBOLD AGUILERA ROBERTO
Se ha registrado nuevo cañero para notificacion: 3323 / TREPP CARRASCO RUDIGER
Se ha registrado nuevo cañero para notificacion: 42231 / PAZ FERNANDEZ RODRIGO
Se ha registrado nuevo cañero para notificacion: 13067 / SAUCEDO CERRUTI SONIA
Se ha registrado nuevo cañero para notificacion: 4914 / GONZALEZ LIMPIAS LUIS ALBERTO
Se ha registrado nuevo cañero para notificacion: 794 / AGUILERA WENDE MARIANO
Se ha registrado nuevo cañero para notificacion: 42023 / RODRIGUEZ ROJAS HUGO ALVARO
Se ha registrado nuevo cañero para notificacion: 9930 / OJEDA GARCIA MIGUEL
Se ha registrado nuevo cañero para notificacion: 86 / AGUILERA TARADELLES JOSE LUIS
Se ha registrado nuevo cañero para notificacion: 4061 / FRITZER PAZ ROMEL
Se ha registrado nuevo cañero para notificacion: 2161 / CORDOVA CAMARA LUCIO
Se ha registrado nuevo cañero para notificacion: 42441 / JUAN CARLOS ORTIZ BANZER
Se ha registrado nuevo cañero para notificacion: 2522 / CARO SONIA GENOVEVA CLAROS DE
Se ha registrado nuevo cañero para notificacion: 41970 / ROCA LANDIVAR ARMANDO

## Cargar a otro dataset los lotes sin planificar

In [33]:
cargar_a_amigocloud_semana_siguiente(lotes_sin_planificar)

Lotes cargado proxima semana ID: 3618
Lotes cargado proxima semana ID: 3619
Lotes cargado proxima semana ID: 3620
Lotes cargado proxima semana ID: 3621
Lotes cargado proxima semana ID: 3622
Lotes cargado proxima semana ID: 3623
Lotes cargado proxima semana ID: 3624
Lotes cargado proxima semana ID: 3625
Lotes cargado proxima semana ID: 3626
Lotes cargado proxima semana ID: 3627
Lotes cargado proxima semana ID: 3628
Lotes cargado proxima semana ID: 3629
Lotes cargado proxima semana ID: 3630
Lotes cargado proxima semana ID: 3631
Lotes cargado proxima semana ID: 3632
Lotes cargado proxima semana ID: 3633
Lotes cargado proxima semana ID: 3634
Lotes cargado proxima semana ID: 3635
Lotes cargado proxima semana ID: 3636
Lotes cargado proxima semana ID: 3637
Lotes cargado proxima semana ID: 3638
Lotes cargado proxima semana ID: 3639
Lotes cargado proxima semana ID: 3640
Lotes cargado proxima semana ID: 3641
Lotes cargado proxima semana ID: 3642
Lotes cargado proxima semana ID: 3643
Lotes cargado proxima semana ID: 3644
Lotes cargado proxima semana ID: 3645
Lotes cargado proxima semana ID: 3646
Lotes cargado proxima semana ID: 3647
Lotes cargado proxima semana ID: 3648
Lotes cargado proxima semana ID: 3649
Lotes cargado proxima semana ID: 3650
Lotes cargado proxima semana ID: 3651
Lotes cargado proxima semana ID: 3652
Lotes cargado proxima semana ID: 3653
Lotes cargado proxima semana ID: 3654
Lotes cargado proxima semana ID: 3655
Lotes cargado proxima semana ID: 3656
Lotes cargado proxima semana ID: 3657
Lotes cargado proxima semana ID: 3658
Lotes cargado proxima semana ID: 3659
Lotes cargado proxima semana ID: 3660
Lotes cargado proxima semana ID: 3661
Lotes cargado proxima semana ID: 3662
Lotes cargado proxima semana ID: 3663
Lotes cargado proxima semana ID: 3664
Lotes cargado proxima semana ID: 3665
Lotes cargado proxima semana ID: 3666
Lotes cargado proxima semana ID: 3667
Lotes cargado proxima semana ID: 3668
Lotes cargado proxima semana ID: 3669
Lotes cargado proxima semana ID: 3670
Lotes cargado proxima semana ID: 3671
Lotes cargado proxima semana ID: 3672
Lotes cargado proxima semana ID: 3673
Lotes cargado proxima semana ID: 3674
Lotes cargado proxima semana ID: 3675
Lotes cargado proxima semana ID: 3676
Lotes cargado proxima semana ID: 3677
Lotes cargado proxima semana ID: 3678
Lotes cargado proxima semana ID: 3679
Lotes cargado proxima semana ID: 3680
Lotes cargado proxima semana ID: 3681
Lotes cargado proxima semana ID: 3682
Lotes cargado proxima semana ID: 3683
Lotes cargado proxima semana ID: 3684
Lotes cargado proxima semana ID: 3685
Lotes cargado proxima semana ID: 3686
Lotes cargado proxima semana ID: 3687
Lotes cargado proxima semana ID: 3688
Lotes cargado proxima semana ID: 3689
Lotes cargado proxima semana ID: 3690
Lotes cargado proxima semana ID: 3691
Lotes cargado proxima semana ID: 3692
Lotes cargado proxima semana ID: 3693
Lotes cargado proxima semana ID: 3694
Lotes cargado proxima semana ID: 3695
Lotes cargado proxima semana ID: 3696
Lotes cargado proxima semana ID: 3697
Lotes cargado proxima semana ID: 3698
Lotes cargado proxima semana ID: 3699
Lotes cargado proxima semana ID: 3700
Lotes cargado proxima semana ID: 3701
Lotes cargado proxima semana ID: 3702
Lotes cargado proxima semana ID: 3703
Lotes cargado proxima semana ID: 3704
Lotes cargado proxima semana ID: 3705
Lotes cargado proxima semana ID: 3706
Lotes cargado proxima semana ID: 3707
Lotes cargado proxima semana ID: 3708
Lotes cargado proxima semana ID: 3709
Lotes cargado proxima semana ID: 3710
Lotes cargado proxima semana ID: 3711
Lotes cargado proxima semana ID: 3712
Lotes cargado proxima semana ID: 3713
Lotes cargado proxima semana ID: 3714
Lotes cargado proxima semana ID: 3715
Lotes cargado proxima semana ID: 3716
Lotes cargado proxima semana ID: 3717
Lotes cargado proxima semana ID: 3718
Lotes cargado proxima semana ID: 3719
Lotes cargado proxima semana ID: 3720
Lotes cargado proxima semana ID: 3721
Lotes cargado proxima semana ID: 3722
Lotes cargado proxima semana ID: 3723
Lotes cargado proxima semana ID: 3724

## Crear KML de lotes planificados

In [44]:
lotes_planificados = obtener_parte_diario_planificado()

In [45]:
len(lotes_planificados)

415

In [46]:
lotes_planificados["area"].sum()

4313.4286250626965

In [47]:
crear_kmls(lotes_planificados)

G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1408
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\771
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1290
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\141
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\270
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\272
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\275
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\19
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1173
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1043
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\661
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\2076
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\2332
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\31
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1953
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1702
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1447
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\551
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\555
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1451
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\300
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1709
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\47
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1585
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\54
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\183
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\55
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\700
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1597
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1726
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\2238
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\320
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\833
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\63
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\325
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\71
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\458
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1228
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1618
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\507
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\2008
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\729
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\218
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\216
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1758
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\741
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1255
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\999
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1770
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1771
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\2158
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\367
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\239
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\1520
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\242
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\114
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\882
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\118
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\375
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\251
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\636
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\2302
G:\\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - EQUIPO AVIACION UTEA\Trichogramma\2026\KML_PLAN\895